### ISSUE TITLE
Store basic auth credentials in Secret for Image with blob source.

### ISSUE THREAD

**Issue by JMesens** [vmware-tanzu/kpack-cli#161]
Currently I pass the basic auth credentials in the blob-url of an Image.

```
        apiVersion: kpack.io/v1alpha1
        kind: Image
        metadata:
          name: image-name
        spec:
          source:
            blob:
              url: https://user:longsupersecurepassword@maven/v1/group/version/artifact-version.jar
```

It would be nice if the user:longsupersecurepassword credentials for basic auth also could be configured through a Secret so they don't have to be passed in the url.
