### ISSUE TITLE
kp can use kp-config ConfigMap for kpack installation state

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#29]
**Outcome**

For commands that require it, `kp` cli tries to read a ConfigMap named `kp-config` from the `kpack` namespace.
Using this ConfigMap, `kp` can fill in values for commands that need:
- The repository used to relocate stack, store, and custom builder images
- a ServiceAccount to attach to resources
- Any future state the cli may want to get

**ConfigMap schema:**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  kp-config
  namespace: kpack
data:
  canonical.repository:
  canonical.repository.serviceaccount:
```
